### ISSUE TITLE
Error deploying stack

### ISSUE THREAD

**Issue by shortjared** [tvanhens/pathery#20]
> Invalid request provided: Queue visibility timeout: 30 seconds is less than Function timeout: 60 seconds

**Comment by shortjared** [comment]
Was able to work around this quick with config settings

```javascript
   indexWriter: {
        memorySize: 1896,
        timeout: Duration.seconds(30),
      },
```

**Comment by tvanhens** [comment]
Doh, that's not good. Fix coming soon.
