### ISSUE TITLE
Panick if running index stats while indexer is being used heavily

### ISSUE THREAD

**Issue by shortjared** [tvanhens/pathery#21]
> thread 'main' panicked at 'Index should be openable: OpenReadError(IoError { io_error: Os { code: 116, kind: StaleNetworkFileHandle, message: "Stale file handle" }, filepath: ".managed.json" })', packages/pathery/src/index.rs:42:43

**Comment by shortjared** [comment]
Solved in 0.2.1ish

**Comment by vassbence** [comment]
@shortjared sorry to necro on an old issue but I was wondering if you could tell me a bit more about how you fixed the issue? Or maybe @tvanhens has some more insights? I'm running a similar thing to what `pathery` does, basically tantivy on EFS and I've just encountered the above problem.
